version: 2

project_name: firstin

before:
  hooks:
    - go mod tidy

builds:
  - id: firstin
    main: ./cmd/firstin/
    binary: firstin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64

archives:
  - id: firstin
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^bug|^fix"
      order: 1
    - title: Improvements
      regexp: "^improvement|^refactor"
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: amishk599
    name: firstin
  draft: false
  prerelease: auto
  replace_existing_artifacts: true
